### ISSUE TITLE
Current mnemonics in Main.sublime-menu do not seem to work and will trigger warnings

### ISSUE THREAD

**Issue by aafulei** [NickHatBoecker/SaveCopyAs#3]
Hi Nick!

Your current `Main.sublime-menu` is

```json
[
    {
        "caption": "File",
        "mnemonic": "f",
        "id": "file",
        "children":
        [
            {
                "caption": "Save Copy As...",
                "mnemonic": "k",
                "command": "save_copy_as"
            }
        ]
    }
]
```

These mnemonics do not seem to work, and will trigger loads of warnings in the Sublime console (`View --> Show Console`)

```
warning: mnemonic f not found in menu caption File
warning: mnemonic k not found in menu caption Save Copy As...
```

The mechanism for a Sublime Text main menu mnemonic is that (for Windows only) the main menu will take a letter from the caption (case-sensitive) and underscore it and use the letter as a shortcut to be triggered by <kbd>alt</kbd>.

That is, you can only choose from letters `S` `a` `v` `e` `C` `o` `p` `y` `A` `s` as your mnemonic for the command `save_copy_as`.

And there is no need to assign a mnemonic or even a caption to `File`. It's already there. You don't want to override it.

I would like to suggest the change below for `Main.sublime-menu`

```json
[
    {
        "id": "file",
        "children":
        [
            {
                "caption": "Save Copy As...",
                "mnemonic": "p",
                "command": "save_copy_as"
            }
        ]
    }
]
```

The exact choice of the letter is up to you, of course.

For your reference, my Sublime Text version is the latest Sublime Text 3, or `3.2.2` (build 3211).

**Comment by NickHatBoecker** [comment]
Hey there,

I'm on build 4121 by now and I can't see any errors in the console on 4, unfortunately.

But I get the point and updated `Main.sublime-menu` according to your suggestion (see https://github.com/NickHatBoecker/SaveCopyAs/pull/4). The [package site](https://packagecontrol.io/packages/Save%20Copy%20As) was also updated by now, so you should be able to update via Sublime Package Control.

Can you please check if the error messages are gone now?

Best regards
Nick

**Comment by aafulei** [comment]
Hi Nick,

Thank you for the reply and update.

> I'm on build 4121 by now and I can't see any errors in the console on 4, unfortunately.

You have to be in Windows in order to see the warnings as mnemonics are for Windows only.

If you are using Windows, maybe there are some settings to turn on/off warnings on the console. I am not sure.

> Can you please check if the error messages are gone now?

Yes. I confirm that the warnings are gone. Thank you!
